name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: self-hosted  # Ensure your self-hosted runner is correctly set up

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache SonarQube Scanner
        uses: actions/cache@v4
        with:
          path: /opt/sonar-scanner
          key: sonar-scanner-cli-7.0.2.4839-Linux-X64
          restore-keys: sonar-scanner-cli-

      - name: Install SonarQube Scanner (if not cached)
        run: |
          if [ ! -d "/opt/sonar-scanner" ]; then
            echo "Installing SonarQube Scanner..."
            mkdir -p /opt/sonar-scanner && cd /opt/sonar-scanner
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
            mv sonar-scanner-5.0.1.3006-linux sonar-scanner
            echo 'export PATH="/opt/sonar-scanner/bin:$PATH"' >> ~/.bashrc
            source ~/.bashrc
          fi

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=FinlogikSecure \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
